#! /bin/sh
#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) 2001 - 2011, Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at http://curl.haxx.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
###########################################################################

prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: curl-config [OPTION]

Available values for OPTION include:

  --built-shared says 'yes' if libcurl was built shared
  --ca        ca bundle install path
  --cc        compiler
  --cflags    pre-processor and compiler flags
  --checkfor [version] check for (lib)curl of the specified version
  --configure the arguments given to configure when building curl
  --features  newline separated list of enabled features
  --help      display this help and exit
  --libs      library linking information
  --prefix    curl install prefix
  --protocols newline separated list of enabled protocols
  --static-libs static libcurl library linking information
  --version   output version information
  --vernum    output the version information as a number (hexadecimal)
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    # this deals with options in the style
    # --option=value and extracts the value part
    # [not currently used]
    -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) value= ;;
    esac

    case "$1" in
    --built-shared)
        echo yes
        ;;

    --ca)
	echo ""/etc/ssl/certs/ca-certificates.crt""
	;;

    --cc)
	echo "arm-eabi-gcc"
	;;

    --prefix)
	echo "$prefix"
	;;

    --feature|--features)
        for feature in SSL libz NTLM NTLM_WB ""; do
            test -n "$feature" && echo "$feature"
        done
	;;

    --protocols)
        for protocol in DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMTP SMTPS TELNET TFTP; do
            echo "$protocol"
        done
	;;

    --version)
	echo libcurl 7.26.0
	exit 0
	;;

    --checkfor)
        checkfor=$2
        cmajor=`echo $checkfor | cut -d. -f1`
        cminor=`echo $checkfor | cut -d. -f2`
        # when extracting the patch part we strip off everything after a
	# dash as that's used for things like version 1.2.3-CVS
	cpatch=`echo $checkfor | cut -d. -f3 | cut -d- -f1`
        checknum=`echo "$cmajor*256*256 + $cminor*256 + ${cpatch:-0}" | bc`
        numuppercase=`echo 071a00 | tr 'a-f' 'A-F'`
        nownum=`echo "obase=10; ibase=16; $numuppercase" | bc`

	if test "$nownum" -ge "$checknum"; then
	  # silent success
	  exit 0
	else
	  echo "requested version $checkfor is newer than existing 7.26.0"
	  exit 1
	fi
	;;

    --vernum)
	echo 071a00
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
       	if test "X${prefix}/include" = "X/usr/include"; then
          echo ""
        else
          echo "-I${prefix}/include"
        fi
       	;;

    --libs)
	if test "X${exec_prefix}/lib" != "X/usr/lib" -a "X${exec_prefix}/lib" != "X/usr/lib64"; then
	   CURLLIBDIR="-L${exec_prefix}/lib "
	else
	   CURLLIBDIR=""
	fi
	if test "Xno" = "Xyes"; then
	  echo ${CURLLIBDIR}-lcurl -lssl -lcrypto -L/home/minggo/android-source/out/target/product/generic/obj/lib -lc -lstdc++ -lm -L/home/minggo/android-source/out/target/product/generic/system/lib -lz -L/home/minggo/android-source/out/target/product/generic/obj/lib -lc -lstdc++ -lm -L/home/minggo/android-source/out/target/product/generic/system/lib
	else
	  echo ${CURLLIBDIR}-lcurl -L/home/minggo/android-source/out/target/product/generic/obj/lib -lc -lstdc++ -lm -L/home/minggo/android-source/out/target/product/generic/system/lib
	fi
	;;

    --static-libs)
	echo ${exec_prefix}/lib/libcurl.a  -lssl -lcrypto -L/home/minggo/android-source/out/target/product/generic/obj/lib -lc -lstdc++ -lm -L/home/minggo/android-source/out/target/product/generic/system/lib -lz -L/home/minggo/android-source/out/target/product/generic/obj/lib -lc -lstdc++ -lm -L/home/minggo/android-source/out/target/product/generic/system/lib
	;;

    --configure)
      echo " '--with-ssl' '--host=arm-linux' 'CC=arm-eabi-gcc' 'LD=arm-eabi-ld' 'AR=arm-eabi-ar' 'STRIP=arm-eabi-strip' 'AS=arm-eabi-as' 'CPPFLAGS=-I /home/minggo/android-source/external/libpng/include     
-I /home/minggo/android-source/external/zlib    
-I /home/minggo/android-source/external/openssl/include
-I /home/minggo/android-source/out/target/product/generic/obj/STATIC_LIBRARIES/libpng_intermediates   
-I /home/minggo/android-source/out/target/product/generic/obj/STATIC_LIBRARIES/libwebcore_intermediates   
-I /home/minggo/android-source/dalvik/libnativehelper/include/nativehelper   
-I /home/minggo/android-source/system/core/include   
-I /home/minggo/android-source/hardware/libhardware/include   
-I /home/minggo/android-source/hardware/libhardware_legacy/include   
-I /home/minggo/android-source/hardware/ril/include   
-I /home/minggo/android-source/dalvik/libnativehelper/include   
-I /home/minggo/android-source/frameworks/base/include   
-I /home/minggo/android-source/frameworks/base/opengl/include   
-I /home/minggo/android-source/frameworks/base/native/include   
-I /home/minggo/android-source/external/skia/include   
-I /home/minggo/android-source/out/target/product/generic/obj/include   
-I /home/minggo/android-source/bionic/libc/arch-arm/include   
-I /home/minggo/android-source/bionic/libc/include   
-I /home/minggo/android-source/bionic/libstdc++/include   
-I /home/minggo/android-source/bionic/libc/kernel/common   
-I /home/minggo/android-source/bionic/libc/kernel/arch-arm   
-I /home/minggo/android-source/bionic/libm/include   
-I /home/minggo/android-source/bionic/libm/include/arch/arm   
-I /home/minggo/android-source/bionic/libthread_db/include 
-I /home/minggo/android-source/system/core/include/arch/linux-arm/ 
-include /home/minggo/android-source/system/core/include/arch/linux-arm/AndroidConfig.h' 'CFLAGS=-nostdlib -fno-exceptions -Wno-multichar -msoft-float -fpic -ffunction-sections -funwind-tables -fstack-protector -Wa,--noexecstack -Werror=format-security -fno-short-enums -march=armv5te -mtune=xscale -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -mthumb-interwork -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wstrict-aliasing=2 -finline-functions -fno-inline-functions-called-once -fgcse-after-reload -frerun-cse-after-loop -frename-registers -mthumb -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64' 'LIBS=-L/home/minggo/android-source/out/target/product/generic/obj/lib -lc -lstdc++ -lm 
-L/home/minggo/android-source/out/target/product/generic/system/lib' 'host_alias=arm-linux'"
    ;;

    *)
        echo "unknown option: $1"
	usage 1
	;;
    esac
    shift
done

exit 0
